name: Daily SEO Update
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run SEO Script
        run: python index-ping.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'SEO-Bot'
          git config --global user.email 'bot@brightlane.io'
          git add .
          git commit -m "Daily Freshness Update - $(date)"
          git push
